# Preface {#preface .unnumbered}

```{r 'setup', include=FALSE}
source("_common.R")
```

## Guidelines

- The project will be kept in sync with the latest versions of both Python and R. 
- It will be ensured that the code can be executed by direct copy-paste and without significantly affecting user work environment
- Equality & Identity tests related to language rules may be hidden to avoid clutter

## Prerequisites

```{r 'R-Version', decorate=TRUE}
strsplit(R.version.string, " ")[[1]][3]           # R Version
```

```{python 'Y-Version', decorate=TRUE}
print(sys.version.split()[0])                     # Python Version

```

## Environment

```{r 'R-Attached-Packages', decorate=TRUE}
# Attached (Basic) Packages in R 
sessionInfo()
```

```{python 'Y-Loaded-Modules', decorate=TRUE}
# Imported (Basic) Modules in Python 
allmodules = [v.__name__ for k, v in globals().items() 
    if type(v) is types.ModuleType and not k.startswith('__')]

len(allmodules)                                   # Count the Loaded Modules

", ".join(allmodules)                             # List Modules

```

```{r 'R-Python-Configuration', decorate=TRUE}
# Python Configuration with R Package 'Reticulate'
py_config()
```

